// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $api_ai from "./routes/api/ai.ts";
import * as $index from "./routes/index.tsx";
import * as $Architect from "./islands/Architect.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/api/ai.ts": $api_ai,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Architect.tsx": $Architect,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
